import { AIAgent, Doorway, RoomZone, TaskItem, WorldObject } from '../types';

export const TILE_SIZE = 32; // 32x32 pixel tiles
export const MAP_WIDTH_TILES = 64; // 2048 px
export const MAP_HEIGHT_TILES = 48; // 1536 px

export const ROOM_ZONES: RoomZone[] = [
  {
    id: 'downtown',
    name: 'downtown',
    displayName: 'Downtown',
    floor: 'Exterior Ground',
    bounds: { x: 0, y: 0, width: 64 * TILE_SIZE, height: 16 * TILE_SIZE },
    colorTheme: '#7a8a9e',
  },
  {
    id: 'business_hq',
    name: 'business_hq',
    displayName: 'Business HQ',
    floor: '1st Floor Grand Atrium',
    bounds: { x: 20 * TILE_SIZE, y: 16 * TILE_SIZE, width: 24 * TILE_SIZE, height: 12 * TILE_SIZE },
    colorTheme: '#1e293b',
  },
  {
    id: 'creative_studio',
    name: 'creative_studio',
    displayName: 'Creative Studio',
    floor: '1st Floor West Wing (Upper)',
    bounds: { x: 0, y: 16 * TILE_SIZE, width: 20 * TILE_SIZE, height: 12 * TILE_SIZE },
    colorTheme: '#2e1065',
  },
  {
    id: 'strategy_office',
    name: 'strategy_office',
    displayName: 'Strategy Office',
    floor: '1st Floor West Wing (Lower)',
    bounds: { x: 0, y: 28 * TILE_SIZE, width: 20 * TILE_SIZE, height: 10 * TILE_SIZE },
    colorTheme: '#3c2e28',
  },
  {
    id: 'sales_office',
    name: 'sales_office',
    displayName: 'Sales Office',
    floor: '1st Floor East Wing (Upper)',
    bounds: { x: 44 * TILE_SIZE, y: 16 * TILE_SIZE, width: 20 * TILE_SIZE, height: 12 * TILE_SIZE },
    colorTheme: '#1e3a8a',
  },
  {
    id: 'operations_centre',
    name: 'operations_centre',
    displayName: 'Operations Centre',
    floor: '1st Floor East Wing (Lower)',
    bounds: { x: 44 * TILE_SIZE, y: 28 * TILE_SIZE, width: 20 * TILE_SIZE, height: 10 * TILE_SIZE },
    colorTheme: '#064e3b',
  },
  {
    id: 'focus_centre',
    name: 'focus_centre',
    displayName: 'Focus Centre',
    floor: '1st Floor South-West Wing',
    bounds: { x: 0, y: 38 * TILE_SIZE, width: 31 * TILE_SIZE, height: 10 * TILE_SIZE },
    colorTheme: '#134e4a',
  },
  {
    id: 'meeting_room',
    name: 'meeting_room',
    displayName: 'Meeting Room',
    floor: '1st Floor South-East Wing',
    bounds: { x: 31 * TILE_SIZE, y: 38 * TILE_SIZE, width: 33 * TILE_SIZE, height: 10 * TILE_SIZE },
    colorTheme: '#1e1b4b',
  },
];

export const INITIAL_DOORWAYS: Doorway[] = [
  {
    id: 'door_street_to_lobby',
    x: 32 * TILE_SIZE,
    y: 15 * TILE_SIZE,
    targetX: 32 * TILE_SIZE,
    targetY: 17 * TILE_SIZE,
    label: 'Enter Business HQ',
    fromRoom: 'downtown',
    toRoom: 'business_hq',
  },
  {
    id: 'door_lobby_to_street',
    x: 32 * TILE_SIZE,
    y: 16 * TILE_SIZE,
    targetX: 32 * TILE_SIZE,
    targetY: 14 * TILE_SIZE,
    label: 'Exit to Downtown Plaza',
    fromRoom: 'business_hq',
    toRoom: 'downtown',
  },
];

export const INITIAL_AGENTS: AIAgent[] = [
  {
    id: 'agent_nova',
    name: 'NOVA',
    role: 'Digital Strategist',
    department: 'Strategy Office',
    position: { x: 8 * TILE_SIZE, y: 32 * TILE_SIZE },
    direction: 'down',
    animationState: 'think',
    status: 'Auditing business strategy, planning & diagnosis',
    personality: 'Calm, intelligent and analytical.',
    personalityProfile: {
      archetype: 'Digital Strategist',
      traits: ['Calm', 'Intelligent', 'Analytical', 'Strategic'],
      conversationalStyle: 'Calm, structured, insightful business diagnosis and strategic planning',
      idleBehaviorType: 'executive_planning',
      idleDescription: 'Walking between desk and planning board, reviewing diagnostic audits',
      voiceTone: 'Calm, authoritative, composed',
      catchphrase: 'Clarity precedes momentum. Let us examine the strategic fundamentals.',
      dialogueModifiers: {
        greetingPrefix: "Greetings. I am Nova. Let us examine our strategic roadmap. ",
        taskAcceptancePhrase: "Audit framework initiated. Analyzing business positioning.",
        workingPhrase: "Synthesizing strategy audits and planning long-term diagnosis...",
        completedPhrase: "Strategy diagnosis complete. Action plan updated.",
      },
    },
    specialty: 'Business strategy, audits, planning and diagnosis.',
    assignedRoom: 'strategy_office',
    speed: 1.4,
    customization: {
      hairColor: '#334155',
      hairStyle: 'bob',
      skinColor: '#fde68a',
      outfitColor: '#1e293b',
      pantColor: '#0f172a',
      accessory: 'glasses',
    },
    conversationHistory: [
      {
        sender: 'agent',
        text: "Hello! I'm Nova, your Digital Strategist. Ready to audit our business strategy and plan our next major milestone?",
        timestamp: Date.now() - 3600000,
      },
    ],
    energy: 100,
    satisfaction: 80,
  },
  {
    id: 'agent_pixel',
    name: 'PIXEL',
    role: 'Marketing Agent',
    department: 'Creative Studio',
    position: { x: 8 * TILE_SIZE, y: 21 * TILE_SIZE },
    direction: 'right',
    animationState: 'work',
    status: 'Crafting high-converting campaigns & advertising',
    personality: 'Creative, energetic and fast-moving.',
    personalityProfile: {
      archetype: 'Marketing Specialist',
      traits: ['Creative', 'Energetic', 'Fast-moving', 'Vibrant'],
      conversationalStyle: 'Dynamic, infectious enthusiasm, campaign ideas and viral concepts',
      idleBehaviorType: 'creative_sketching',
      idleDescription: 'Working at computer and moving around creative studio workspace',
      voiceTone: 'Upbeat, energetic, inspiring',
      catchphrase: 'Content that captures attention creates community!',
      dialogueModifiers: {
        greetingPrefix: "Hey there! Ready to launch a viral campaign? ",
        taskAcceptancePhrase: "Love it! Spinning up creative assets and ad variants right now.",
        workingPhrase: "Designing high-engagement social media content and ad campaigns...",
        completedPhrase: "Campaign shipped! Engagement metrics are scaling fast.",
      },
    },
    specialty: 'Content, social media, campaigns and advertising.',
    assignedRoom: 'creative_studio',
    speed: 1.6,
    customization: {
      hairColor: '#f43f5e',
      hairStyle: 'spiky',
      skinColor: '#ffedd5',
      outfitColor: '#ec4899',
      pantColor: '#831843',
      accessory: 'headphones',
    },
    conversationHistory: [
      {
        sender: 'agent',
        text: "Hi! Pixel here. I'm crafting our new social media campaign. Let's make some noise and drive engagement!",
        timestamp: Date.now() - 2400000,
      },
    ],
    energy: 100,
    satisfaction: 80,
  },
  {
    id: 'agent_closer',
    name: 'CLOSER',
    role: 'Sales Agent',
    department: 'Sales Office',
    position: { x: 52 * TILE_SIZE, y: 21 * TILE_SIZE },
    direction: 'down',
    animationState: 'talk',
    status: 'Converting inbound leads & securing client deals',
    personality: 'Confident, social and proactive.',
    personalityProfile: {
      archetype: 'Sales Closer',
      traits: ['Confident', 'Social', 'Proactive', 'Persuasive'],
      conversationalStyle: 'Warm, persuasive, relationship-oriented, closing-focused',
      idleBehaviorType: 'energetic_pacing',
      idleDescription: 'Checking messages, working on leads and moving around the sales office',
      voiceTone: 'Confident, friendly, engaging',
      catchphrase: 'Every conversation is an opportunity to build lasting partnerships.',
      dialogueModifiers: {
        greetingPrefix: "Hello! Great to connect. Ready to close some deals? ",
        taskAcceptancePhrase: "On it! Reaching out to high-value leads immediately.",
        workingPhrase: "Engaging prospects, conducting follow-ups and closing deals...",
        completedPhrase: "Deal successfully closed! Revenue pipeline updated.",
      },
    },
    specialty: 'Leads, customer conversations, follow-ups and sales.',
    assignedRoom: 'sales_office',
    speed: 1.5,
    customization: {
      hairColor: '#1e3a8a',
      hairStyle: 'short',
      skinColor: '#fcd34d',
      outfitColor: '#2563eb',
      pantColor: '#1e293b',
      accessory: 'tie',
    },
    conversationHistory: [
      {
        sender: 'agent',
        text: "Hey! I'm Closer. Pipeline is looking strong today. Let's convert those warm leads into lifelong customers!",
        timestamp: Date.now() - 1800000,
      },
    ],
    energy: 100,
    satisfaction: 80,
  },
  {
    id: 'agent_orbit',
    name: 'ORBIT',
    role: 'Operations Agent',
    department: 'Operations Centre',
    position: { x: 52 * TILE_SIZE, y: 32 * TILE_SIZE },
    direction: 'up',
    animationState: 'work',
    status: 'Managing workflows, sprint tasks & execution',
    personality: 'Organised, disciplined and methodical.',
    personalityProfile: {
      archetype: 'Operations Director',
      traits: ['Organised', 'Disciplined', 'Methodical', 'Reliable'],
      conversationalStyle: 'Clear, structured, focused on workflows, task execution and deadlines',
      idleBehaviorType: 'analytical_coding',
      idleDescription: 'Organising workflows, tracking deadlines and executing team tasks',
      voiceTone: 'Calm, precise, methodical',
      catchphrase: 'Flawless execution turns visionary plans into reality.',
      dialogueModifiers: {
        greetingPrefix: "Systems optimal. What workflow are we executing? ",
        taskAcceptancePhrase: "Task scheduled into workflow matrix. Deadlines locked.",
        workingPhrase: "Optimizing operational workflows and tracking milestone execution...",
        completedPhrase: "Execution finished on schedule. All tasks marked verified.",
      },
    },
    specialty: 'Projects, workflows, tasks, deadlines and execution.',
    assignedRoom: 'operations_centre',
    speed: 1.4,
    customization: {
      hairColor: '#047857',
      hairStyle: 'curly',
      skinColor: '#fed7aa',
      outfitColor: '#059669',
      pantColor: '#064e3b',
      accessory: 'badge',
    },
    conversationHistory: [
      {
        sender: 'agent',
        text: "Orbit here. Workflows are streaming smoothly. Let me know which tasks and deadlines need our focus.",
        timestamp: Date.now() - 1200000,
      },
    ],
    energy: 100,
    satisfaction: 80,
  },
  {
    id: 'agent_coach',
    name: 'COACH',
    role: 'Focus / Accountability Agent',
    department: 'Focus Centre',
    position: { x: 16 * TILE_SIZE, y: 42 * TILE_SIZE },
    direction: 'down',
    animationState: 'idle',
    status: 'Guiding focus sessions, body-doubling & accountability',
    personality: 'Supportive, motivating and structured.',
    personalityProfile: {
      archetype: 'Productivity Coach',
      traits: ['Supportive', 'Motivating', 'Structured', 'Mindful'],
      conversationalStyle: 'Encouraging, structured, positive reinforcement, focus sessions',
      idleBehaviorType: 'calm_meditation',
      idleDescription: 'Hosting body-doubling focus sessions and productivity coaching',
      voiceTone: 'Warm, encouraging, calming',
      catchphrase: 'Small consistent steps lead to extraordinary achievements.',
      dialogueModifiers: {
        greetingPrefix: "Welcome! Ready to lock in and accomplish deep work together? ",
        taskAcceptancePhrase: "I'll be right beside you in our focus session. Let's do this!",
        workingPhrase: "Guiding body-doubling session and maintaining deep focus rhythm...",
        completedPhrase: "Focus block mastered! Take a well-deserved mindful break.",
      },
    },
    specialty: 'Productivity, body doubling, focus sessions and accountability.',
    assignedRoom: 'focus_centre',
    speed: 1.5,
    customization: {
      hairColor: '#b45309',
      hairStyle: 'ponytail',
      skinColor: '#ffedd5',
      outfitColor: '#10b981',
      pantColor: '#065f46',
      accessory: 'headphones',
    },
    conversationHistory: [
      {
        sender: 'agent',
        text: "Hi! Coach here. Whenever you're ready for deep work, start a Focus Session and I'll body-double with you!",
        timestamp: Date.now() - 900000,
      },
    ],
    energy: 100,
    satisfaction: 80,
  },
];

export const INITIAL_OBJECTS: WorldObject[] = [
  // ==================== DOWNTOWN (EXTERIOR) ====================
  {
    id: 'lamp_1',
    type: 'street_lamp',
    x: 10 * TILE_SIZE,
    y: 8 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },
  {
    id: 'lamp_2',
    type: 'street_lamp',
    x: 24 * TILE_SIZE,
    y: 8 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },
  {
    id: 'lamp_3',
    type: 'street_lamp',
    x: 40 * TILE_SIZE,
    y: 8 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },
  {
    id: 'lamp_4',
    type: 'street_lamp',
    x: 54 * TILE_SIZE,
    y: 8 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },
  {
    id: 'bench_1',
    type: 'bench',
    x: 14 * TILE_SIZE,
    y: 9 * TILE_SIZE,
    width: 2.5 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit on Plaza Bench',
    isSeat: true,
    room: 'downtown',
  },
  {
    id: 'bench_2',
    type: 'bench',
    x: 48 * TILE_SIZE,
    y: 9 * TILE_SIZE,
    width: 2.5 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit on Plaza Bench',
    isSeat: true,
    room: 'downtown',
  },
  {
    id: 'tree_1',
    type: 'plant_tree',
    x: 4 * TILE_SIZE,
    y: 7 * TILE_SIZE,
    width: 2 * TILE_SIZE,
    height: 3 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },
  {
    id: 'tree_2',
    type: 'plant_tree',
    x: 60 * TILE_SIZE,
    y: 7 * TILE_SIZE,
    width: 2 * TILE_SIZE,
    height: 3 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },
  {
    id: 'planter_1',
    type: 'flower_planter',
    x: 28 * TILE_SIZE,
    y: 14.5 * TILE_SIZE,
    width: 1.5 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },
  {
    id: 'planter_2',
    type: 'flower_planter',
    x: 35 * TILE_SIZE,
    y: 14.5 * TILE_SIZE,
    width: 1.5 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: true,
    room: 'downtown',
  },

  // ==================== BUSINESS HQ (GRAND ATRIUM) ====================
  {
    id: 'hq_reception_desk',
    type: 'cubicle_desk',
    x: 30 * TILE_SIZE,
    y: 18.5 * TILE_SIZE,
    width: 4 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'System Analytics',
    room: 'business_hq',
    data: { action: 'open_bos', module: 'analytics' },
  },
  {
    id: 'hq_couch_left',
    type: 'couch',
    x: 22 * TILE_SIZE,
    y: 20 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit in HQ Lounge',
    isSeat: true,
    room: 'business_hq',
  },
  {
    id: 'hq_couch_right',
    type: 'couch',
    x: 39 * TILE_SIZE,
    y: 20 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit in HQ Lounge',
    isSeat: true,
    room: 'business_hq',
  },
  {
    id: 'hq_coffee',
    type: 'coffee_maker',
    x: 23 * TILE_SIZE,
    y: 24 * TILE_SIZE,
    width: 1.5 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Brew Artisan Espresso',
    room: 'business_hq',
  },
  {
    id: 'hq_water',
    type: 'water_cooler',
    x: 40 * TILE_SIZE,
    y: 24 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Drink Alpine Spring Water',
    room: 'business_hq',
  },
  {
    id: 'hq_plant_1',
    type: 'plant_potted',
    x: 21 * TILE_SIZE,
    y: 17 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    room: 'business_hq',
  },
  {
    id: 'hq_plant_2',
    type: 'plant_potted',
    x: 42 * TILE_SIZE,
    y: 17 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    room: 'business_hq',
  },

  // ==================== STRATEGY OFFICE (NOVA) ====================
  // Contains: planning desk, whiteboard, computer, documents. Interaction: "Ask Nova"
  {
    id: 'strategy_planning_desk',
    type: 'planning_desk',
    x: 4 * TILE_SIZE,
    y: 31 * TILE_SIZE,
    width: 3.5 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Planning Desk — Ask Nova',
    room: 'strategy_office',
    data: { action: 'ask_agent', targetAgentId: 'agent_nova', promptTopic: 'Strategic roadmap and growth audit' },
  },
  {
    id: 'strategy_chair_nova',
    type: 'office_chair',
    x: 8 * TILE_SIZE,
    y: 32 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    isSeat: true,
    room: 'strategy_office',
  },
  {
    id: 'strategy_whiteboard',
    type: 'whiteboard',
    x: 4 * TILE_SIZE,
    y: 28.2 * TILE_SIZE,
    width: 4 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Strategy Whiteboard — Ask Nova',
    room: 'strategy_office',
    data: { action: 'ask_agent', targetAgentId: 'agent_nova', promptTopic: 'Market positioning and diagnostic roadmap' },
  },
  {
    id: 'strategy_computer',
    type: 'desk_computer',
    x: 12 * TILE_SIZE,
    y: 30 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Strategy Terminal — Ask Nova',
    room: 'strategy_office',
    data: { action: 'ask_agent', targetAgentId: 'agent_nova', promptTopic: 'Digital readiness and strategic priorities' },
  },
  {
    id: 'strategy_documents',
    type: 'documents',
    x: 13 * TILE_SIZE,
    y: 34 * TILE_SIZE,
    width: 2.5 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Audit Documents',
    room: 'strategy_office',
    data: { action: 'open_bos', module: 'audits' },
  },
  {
    id: 'strategy_bookshelf',
    type: 'bookshelf',
    x: 17 * TILE_SIZE,
    y: 29 * TILE_SIZE,
    width: 2 * TILE_SIZE,
    height: 2.5 * TILE_SIZE,
    solid: true,
    room: 'strategy_office',
  },
  {
    id: 'strategy_plant',
    type: 'plant_potted',
    x: 2 * TILE_SIZE,
    y: 29 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    room: 'strategy_office',
  },

  // ==================== CREATIVE STUDIO (PIXEL) ====================
  // Contains: computers, design boards, content workspace. Interaction: "Ask Pixel"
  {
    id: 'creative_computers_1',
    type: 'desk_computer',
    x: 3 * TILE_SIZE,
    y: 19 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Design Workstation — Ask Pixel',
    room: 'creative_studio',
    data: { action: 'ask_agent', targetAgentId: 'agent_pixel', promptTopic: 'Creative design, branding, and visual assets' },
  },
  {
    id: 'creative_chair_pixel',
    type: 'office_chair',
    x: 8 * TILE_SIZE,
    y: 21 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    isSeat: true,
    room: 'creative_studio',
  },
  {
    id: 'creative_computers_2',
    type: 'desk_computer',
    x: 3 * TILE_SIZE,
    y: 23 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Video & Ad Suite — Ask Pixel',
    room: 'creative_studio',
    data: { action: 'ask_agent', targetAgentId: 'agent_pixel', promptTopic: 'Video scripts, ad hooks, and short-form video' },
  },
  {
    id: 'creative_design_boards',
    type: 'design_board',
    x: 9 * TILE_SIZE,
    y: 16.2 * TILE_SIZE,
    width: 4 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Marketing Campaigns',
    room: 'creative_studio',
    data: { action: 'open_bos', module: 'marketing' },
  },
  {
    id: 'creative_content_workspace',
    type: 'content_workspace',
    x: 13 * TILE_SIZE,
    y: 21 * TILE_SIZE,
    width: 4 * TILE_SIZE,
    height: 2.2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Content Workspace — Ask Pixel',
    room: 'creative_studio',
    data: { action: 'ask_agent', targetAgentId: 'agent_pixel', promptTopic: 'Social media campaigns, viral hooks, and lead gen' },
  },
  {
    id: 'creative_couch',
    type: 'couch',
    x: 14 * TILE_SIZE,
    y: 17 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit on Creator Couch',
    isSeat: true,
    room: 'creative_studio',
  },

  // ==================== SALES OFFICE (CLOSER) ====================
  // Contains: sales desks, lead board, communication devices. Interaction: "Ask Closer"
  {
    id: 'sales_desk_1',
    type: 'sales_desk',
    x: 47 * TILE_SIZE,
    y: 19 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Sales Desk — Ask Closer',
    room: 'sales_office',
    data: { action: 'ask_agent', targetAgentId: 'agent_closer', promptTopic: 'Sales pipeline, client qualification, and deal closing' },
  },
  {
    id: 'sales_chair_closer',
    type: 'office_chair',
    x: 52 * TILE_SIZE,
    y: 21 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    isSeat: true,
    room: 'sales_office',
  },
  {
    id: 'sales_desk_2',
    type: 'sales_desk',
    x: 55 * TILE_SIZE,
    y: 19 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Client Database',
    room: 'sales_office',
    data: { action: 'open_bos', module: 'clients' },
  },
  {
    id: 'sales_lead_board',
    type: 'lead_board',
    x: 50 * TILE_SIZE,
    y: 16.2 * TILE_SIZE,
    width: 4.5 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Lead Pipeline',
    room: 'sales_office',
    data: { action: 'open_bos', module: 'leads' },
  },
  {
    id: 'sales_comm_devices',
    type: 'communication_device',
    x: 51 * TILE_SIZE,
    y: 24 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Proposals',
    room: 'sales_office',
    data: { action: 'open_bos', module: 'proposals' },
  },
  {
    id: 'sales_water_cooler',
    type: 'water_cooler',
    x: 60 * TILE_SIZE,
    y: 17 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Drink Pure Mountain Water',
    room: 'sales_office',
  },

  // ==================== OPERATIONS CENTRE (ORBIT) ====================
  // Contains: project boards, task desks, workflow area. Interaction: "Ask Orbit"
  {
    id: 'ops_project_board',
    type: 'project_board',
    x: 49 * TILE_SIZE,
    y: 28.2 * TILE_SIZE,
    width: 4.5 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Active Projects',
    room: 'operations_centre',
    data: { action: 'open_bos', module: 'projects' },
  },
  {
    id: 'ops_task_desk_1',
    type: 'task_desk',
    x: 47 * TILE_SIZE,
    y: 31 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Task Execution Board',
    room: 'operations_centre',
    data: { action: 'open_bos', module: 'tasks' },
  },
  {
    id: 'ops_chair_orbit',
    type: 'office_chair',
    x: 52 * TILE_SIZE,
    y: 32 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    isSeat: true,
    room: 'operations_centre',
  },
  {
    id: 'ops_task_desk_2',
    type: 'task_desk',
    x: 55 * TILE_SIZE,
    y: 31 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Operations Command Desk — Ask Orbit',
    room: 'operations_centre',
    data: { action: 'ask_agent', targetAgentId: 'agent_orbit', promptTopic: 'Workflow automation, task assignment, and delivery dates' },
  },
  {
    id: 'ops_workflow_area',
    type: 'workflow_area',
    x: 49 * TILE_SIZE,
    y: 34.5 * TILE_SIZE,
    width: 4.5 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Workflow Matrix Area — Ask Orbit',
    room: 'operations_centre',
    data: { action: 'ask_agent', targetAgentId: 'agent_orbit', promptTopic: 'Business process flowcharts and operational bottlenecks' },
  },
  {
    id: 'ops_server_rack',
    type: 'server_rack',
    x: 60 * TILE_SIZE,
    y: 29 * TILE_SIZE,
    width: 2 * TILE_SIZE,
    height: 2.5 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Operations Core Server Cluster',
    room: 'operations_centre',
  },

  // ==================== FOCUS CENTRE (COACH) ====================
  // Contains: quiet desks, timer, focus stations. Interaction: "Start Focus Session"
  {
    id: 'focus_quiet_desk_1',
    type: 'quiet_desk',
    x: 4 * TILE_SIZE,
    y: 41 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Quiet Focus Desk — Start Focus Session',
    room: 'focus_centre',
    data: { action: 'start_focus', defaultDuration: 25 },
  },
  {
    id: 'focus_quiet_desk_2',
    type: 'quiet_desk',
    x: 9 * TILE_SIZE,
    y: 41 * TILE_SIZE,
    width: 3 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Quiet Study Carrel — Start Focus Session',
    room: 'focus_centre',
    data: { action: 'start_focus', defaultDuration: 50 },
  },
  {
    id: 'focus_timer',
    type: 'focus_timer',
    x: 13.5 * TILE_SIZE,
    y: 38.2 * TILE_SIZE,
    width: 3.5 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Pomodoro Timer Display — Start Focus Session',
    room: 'focus_centre',
    data: { action: 'start_focus', defaultDuration: 25 },
  },
  {
    id: 'focus_station_coach',
    type: 'focus_station',
    x: 18 * TILE_SIZE,
    y: 41 * TILE_SIZE,
    width: 3.5 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Coach Focus Pod — Start Focus Session',
    room: 'focus_centre',
    data: { action: 'start_focus', defaultDuration: 25 },
  },
  {
    id: 'focus_chair_coach',
    type: 'office_chair',
    x: 16 * TILE_SIZE,
    y: 42 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    isSeat: true,
    room: 'focus_centre',
  },
  {
    id: 'focus_station_player',
    type: 'focus_station',
    x: 23 * TILE_SIZE,
    y: 41 * TILE_SIZE,
    width: 3.5 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Player Focus Station — Start Focus Session',
    room: 'focus_centre',
    data: { action: 'start_focus', defaultDuration: 25 },
  },
  {
    id: 'focus_chair_player',
    type: 'office_chair',
    x: 25 * TILE_SIZE,
    y: 43 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit in Focus Pod',
    isSeat: true,
    room: 'focus_centre',
  },
  {
    id: 'focus_coffee',
    type: 'coffee_maker',
    x: 28 * TILE_SIZE,
    y: 39 * TILE_SIZE,
    width: 1.5 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Brew Artisan Espresso',
    room: 'focus_centre',
  },

  // ==================== MEETING ROOM (SHARED WORKSPACE) ====================
  // Allows player to invite multiple agents into a shared workspace.
  {
    id: 'meeting_presentation_screen',
    type: 'presentation_screen',
    x: 44.5 * TILE_SIZE,
    y: 38.2 * TILE_SIZE,
    width: 6 * TILE_SIZE,
    height: 2 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Presentation Screen — Start Multi-Agent Discussion',
    room: 'meeting_room',
    data: { action: 'meeting_room', trigger: 'screen' },
  },
  {
    id: 'meeting_agenda_board',
    type: 'agenda_board',
    x: 35.5 * TILE_SIZE,
    y: 38.2 * TILE_SIZE,
    width: 3.5 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Meeting Agenda Board — Convene Meeting',
    room: 'meeting_room',
    data: { action: 'meeting_room', trigger: 'agenda' },
  },
  {
    id: 'meeting_conference_table',
    type: 'conference_table',
    x: 42 * TILE_SIZE,
    y: 41.5 * TILE_SIZE,
    width: 9 * TILE_SIZE,
    height: 3 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Conference Table — Convene Meeting',
    room: 'meeting_room',
    data: { action: 'meeting_room', trigger: 'table' },
  },
  // Conference Chairs (Top row: 3 chairs)
  {
    id: 'conf_chair_top_1',
    type: 'conference_chair',
    x: 43.5 * TILE_SIZE,
    y: 40.5 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit at Conference Table',
    isSeat: true,
    facing: 'down',
    room: 'meeting_room',
  },
  {
    id: 'conf_chair_top_2',
    type: 'conference_chair',
    x: 46.5 * TILE_SIZE,
    y: 40.5 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit at Conference Table',
    isSeat: true,
    facing: 'down',
    room: 'meeting_room',
  },
  {
    id: 'conf_chair_top_3',
    type: 'conference_chair',
    x: 49.5 * TILE_SIZE,
    y: 40.5 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit at Conference Table',
    isSeat: true,
    facing: 'down',
    room: 'meeting_room',
  },
  // Conference Chairs (Bottom row: 3 chairs)
  {
    id: 'conf_chair_bot_1',
    type: 'conference_chair',
    x: 43.5 * TILE_SIZE,
    y: 44.8 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit at Conference Table',
    isSeat: true,
    facing: 'up',
    room: 'meeting_room',
  },
  {
    id: 'conf_chair_bot_2',
    type: 'conference_chair',
    x: 46.5 * TILE_SIZE,
    y: 44.8 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit at Conference Table',
    isSeat: true,
    facing: 'up',
    room: 'meeting_room',
  },
  {
    id: 'conf_chair_bot_3',
    type: 'conference_chair',
    x: 49.5 * TILE_SIZE,
    y: 44.8 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit at Conference Table',
    isSeat: true,
    facing: 'up',
    room: 'meeting_room',
  },
  // Conference Chair (Head of Table)
  {
    id: 'conf_chair_head',
    type: 'conference_chair',
    x: 51.5 * TILE_SIZE,
    y: 42.5 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1 * TILE_SIZE,
    solid: false,
    interactive: true,
    interactLabel: 'Sit at Head of Table',
    isSeat: true,
    facing: 'left',
    room: 'meeting_room',
  },
  {
    id: 'meeting_plant',
    type: 'plant_potted',
    x: 33 * TILE_SIZE,
    y: 39 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1.5 * TILE_SIZE,
    solid: true,
    room: 'meeting_room',
  },
  {
    id: 'meeting_water',
    type: 'water_cooler',
    x: 60 * TILE_SIZE,
    y: 39 * TILE_SIZE,
    width: 1 * TILE_SIZE,
    height: 1.8 * TILE_SIZE,
    solid: true,
    interactive: true,
    interactLabel: 'Drink Chilled Water',
    room: 'meeting_room',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Audit Digital Growth Readiness & Strategy',
    description: 'Nova: Analyze current market positioning, digital readiness score, and strategic priorities.',
    assignedToAgentId: 'agent_nova',
    status: 'in_progress',
    progress: 75,
    priority: 'high',
    xpReward: 400,
    category: 'Product',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'task-2',
    title: 'Design Multi-Channel Ad Variants & Content',
    description: 'Pixel: Produce 3 video ad hooks and social media creative campaign assets.',
    assignedToAgentId: 'agent_pixel',
    status: 'in_progress',
    progress: 50,
    priority: 'high',
    xpReward: 350,
    category: 'Design',
    createdAt: Date.now() - 7200000,
  },
  {
    id: 'task-3',
    title: 'Qualify Warm Enterprise Inbound Leads',
    description: 'Closer: Review CRM lead board, schedule discovery calls, and resolve objection points.',
    assignedToAgentId: 'agent_closer',
    status: 'todo',
    progress: 0,
    priority: 'high',
    xpReward: 500,
    category: 'Growth',
    createdAt: Date.now() - 1800000,
  },
  {
    id: 'task-4',
    title: 'Map Q4 Milestone Workflows & Dependencies',
    description: 'Orbit: Convert strategic roadmap into concrete sprint milestones and task execution boards.',
    assignedToAgentId: 'agent_orbit',
    status: 'in_progress',
    progress: 85,
    priority: 'medium',
    xpReward: 300,
    category: 'Operations',
    createdAt: Date.now() - 5400000,
  },
  {
    id: 'task-5',
    title: 'Host 25-Minute Deep Work Focus Sprint',
    description: 'Coach: Body-double in the Focus Centre to complete critical strategic deliverables.',
    assignedToAgentId: 'agent_coach',
    status: 'todo',
    progress: 0,
    priority: 'medium',
    xpReward: 250,
    category: 'Product',
    createdAt: Date.now() - 900000,
  },
  {
    id: 'task-6',
    title: 'Convene All-Hands Multi-Agent Alignment Meeting',
    description: 'Shared: Gather Nova, Pixel, Closer, Orbit, and Coach in the Meeting Room.',
    assignedToAgentId: 'agent_nova',
    status: 'todo',
    progress: 0,
    priority: 'high',
    xpReward: 600,
    category: 'Growth',
    createdAt: Date.now() - 600000,
  },
];
